name: Hardhat Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18  # Usa la TUA versione di Node.js

    - name: Install dependencies
      run: npm install

    - name: Compile contracts
      run: npx hardhat compile

    - name: Run tests
      run: npx hardhat test
      env:  # <-- QUESTA È LA SEZIONE IMPORTANTE
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
        AMOY_RPC_URL: ${{ secrets.AMOY_RPC_URL }}
        BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
        BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
        SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }} #Assicurati che ci sia
        POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
        BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
